# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('problems', '0002_auto_20180307_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setter', to='accounts.Profile'),
        ),
    ]
