# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('problems', '0003_problem_setter'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
