# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
