# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import problems.models
import problems.storage


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_testcase_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FileField(storage=problems.storage.OverwriteStorage(), upload_to=problems.models.upload_input),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FileField(storage=problems.storage.OverwriteStorage(), upload_to=problems.models.upload_output),
        ),
    ]
