# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20180413_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together=set([('problem', 'testcase')]),
        ),
    ]
