# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20180415_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=5),
        ),
    ]
