# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
