# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_unlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], default='EASY', max_length=5),
        ),
    ]
