# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20180429_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=5),
        ),
    ]
