# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import problems.models
import problems.storage


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_auto_20180430_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_checker',
            field=models.FileField(blank=True, null=True, storage=problems.storage.OverwriteStorage(), upload_to=problems.models.upload_solution),
        ),
    ]
