# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180425_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'ACCEPTED'), ('WA', 'WRONG ANSWER'), ('RE', 'RUNTIME ERROR'), ('TLE', 'TIME LIMIT EXCEEDED'), ('IE', 'INTERNAL ERROR'), ('R', 'RUNNING'), ('CE', 'COMPILATION_ERROR')], default='R', max_length=3),
        ),
    ]
