# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_problem_level'),
        ('submissions', '0006_submission_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSubmissionTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'ACCEPTED'), ('WA', 'WRONG ANSWER'), ('RE', 'RUNTIME ERROR'), ('TLE', 'TIME LIMIT EXCEEDED'), ('IE', 'INTERNAL ERROR'), ('R', 'RUNNING')], default='R', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='contestsubmissiontasks',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.ContestSubmission'),
        ),
        migrations.AddField(
            model_name='contestsubmissiontasks',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.TestCase'),
        ),
    ]
