# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20180428_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
