# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20180428_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
