# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_auto_20180428_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
