# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20180429_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
