# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180307_0941'),
        ('accounts', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestshaveproblems',
            unique_together=set([('problem', 'contest')]),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('user', 'contest')]),
        ),
    ]
