# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180307_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
