# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
