# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20180428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
